Update openafs-client-Solaris
Some cosmetic changes
Remove all PATH from commands

diff --git a/files/openafs-client-Solaris b/files/openafs-client-Solaris
--- a/files/openafs-client-Solaris
+++ b/files/openafs-client-Solaris
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# Copyright (c) 2015 AFS-Core Ericsson
-# Version v1.8, 2015-02-19
+# Copyright (c) 2016 AFS-Core Ericsson
+# Version v1.9, 2016-03-11
 #
 # openafs-client  Start/Stop the OpenAFS Client
 # rc script for AFS on Solaris 8/9/10/11 or OpenSolaris-based platforms
@@ -25,8 +25,16 @@ FALSE=1
 AFSD_ARGS=${AFSD_ARGS:-"-dynroot -afsdb -nosettime"}
 
 # Need the commands pgrep, awk, fs
-PATH=/sbin:/bin:/usr/bin:/usr/sbin:/usr/proc/bin:/usr/afsws/bin:/usr/afsws/etc:/usr/afs/bin:/usr/afs/etc:/opt/afssw/bin:/opt/afssw/etc:/usr/afsw/bin:/usr/afsw/sbin:/usr/afsw/etc:/usr/vice/bin:/usr/vice/etc:"$PATH"
+PATH=/sbin:/bin:/usr/bin:/usr/sbin:/usr/proc/bin:/usr/afsws/bin:/usr/afsws/etc:/usr/afs/bin:/usr/afs/etc:/opt/afssw/bin:/opt/afssw/etc:/usr/afsw/bin:/usr/afsw/sbin:/usr/afsw/etc:/usr/vice/bin:/usr/vice/etc
 export PATH
+
+noroot_check() {
+  if [ "`whoami | awk '{print $1}' | cut -f2 -d\!`" != "root" ]; then
+    return 0
+  else
+    return 1
+  fi
+}
 
 setsuid() {
   if [ -f $SUIDCELLS ]; then
@@ -38,34 +46,20 @@ setsuid() {
 }
 
 get_cell() {
-  CELL=`/usr/bin/fs wscell 2>/dev/null | sed -e "s/.*to cell '\(.*\)'/\1/"`
+  CELL=`fs wscell 2>/dev/null | sed -e "s/.*to cell '\(.*\)'/\1/"`
   if [ -z "$CELL" ]; then
     CELL="$DEFAULTCELL"
   fi
 }
 
 setsysname() {
-  type sys 1>/dev/null 2>/dev/null
-  if [ $? -eq 0 ]; then
-    SYS="$(sys)"
-    ADDSYS=`echo $SYS | sed -e 's/_511$/_510/'`
-    SYSNAMELIST="${SYS} ${ADDSYS}"
+  if { SYS=`sys`; } >/dev/null 2>&1; then
+    ADDSYS=`echo "$SYS" | sed -n 's/_511$/_510/p'`
+    if [ -n "$ADDSYS" ]; then
+      echo "Setting sysname: $SYS $ADDSYS"
+      fs sysname "$SYS" "$ADDSYS" >/dev/null
+    fi
   fi
-  # Set the sysname
-  if [ -n "$SYSNAMELIST" ] ; then
-    _FLAG=0
-    _CMD=""
-    for SYSNAME in $SYSNAMELIST ; do
-      if [ $_FLAG == "1" ] ; then
-        _CMD="$_CMD -newsys $SYSNAME"
-      else
-        _FLAG=1
-        _CMD="fs sysname -newsys $SYSNAME"
-      fi
-    done
-  fi
-  echo "Setting sysname: $SYSNAMELIST"
-  $_CMD > /dev/null
 }
 
 chkafsd() {
@@ -86,73 +80,76 @@ issol11() {
 }
 
 case $1 in
-'start')
-
-# Not starting afsd on containers (non global zone)
-if uname -v | grep Virtual >/dev/null || { zonename; } 2>/dev/null | fgrep -vx global >/dev/null; then
-  echo "Solaris Non-Global Zone: afsd will not start and is not needed !"
-  exit
-fi
-
-if issol11; then
-  DRVFS=drv
-else
-  DRVFS=fs
-  #
-  # Make sure afs exists in /etc/name_to_sysnum
-  #
-  if grep -s "afs" /etc/name_to_sysnum > /dev/null; then
-    echo "Entry for afs already exists in /etc/name_to_sysnum"
-  else
-    echo "Creating entry for afs in /etc/name_to_sysnum"
-    cp /etc/name_to_sysnum /etc/name_to_sysnum.orig
-    sed '/nfs/i\
-afs			65' /etc/name_to_sysnum > /tmp/name_to_sysnum
-    mv /tmp/name_to_sysnum /etc/name_to_sysnum
-    echo "Reboot the system now for new /etc/name_to_sysnum to take effect"
-    #reboot
-  fi
-fi
-
-## Check to see that /bin/isalist exists and is executable
-if [ ! -x /bin/isalist ] ;then
-      echo "/bin/isalist not executable"
+  'start')
+	  if noroot_check; then
+	    echo "Script has to be run as root"
+	    exit 1
+	  fi
+    # Not starting afsd on containers (non global zone)
+    if uname -v | grep Virtual >/dev/null || { zonename; } 2>/dev/null | fgrep -vx global >/dev/null; then
+      echo "Solaris Non-Global Zone: afsd will not start and is not needed !"
+      exit
+    fi
+    
+    if issol11; then
+      DRVFS=drv
+    else
+      DRVFS=fs
+      #
+      # Make sure afs exists in /etc/name_to_sysnum
+      #
+      if grep -s "afs" /etc/name_to_sysnum > /dev/null; then
+        echo "Entry for afs already exists in /etc/name_to_sysnum"
+      else
+        echo "Creating entry for afs in /etc/name_to_sysnum"
+        cp /etc/name_to_sysnum /etc/name_to_sysnum.orig
+        sed '/nfs/i\
+    afs     65' /etc/name_to_sysnum > /tmp/name_to_sysnum
+        mv /tmp/name_to_sysnum /etc/name_to_sysnum
+        echo "Reboot the system now for new /etc/name_to_sysnum to take effect"
+        #reboot
+      fi
+    fi
+    
+    ## Check to see that /bin/isalist exists and is executable
+    if { ! isalist; } >/dev/null 2>&1; then
+      echo "isalist not available"
       exit 1;
-fi
-
-## Determine if we are running the 64 bit OS
-## If sparcv9 then the location of the afs and nfs extensions differ
-
-case `/bin/isalist` in
-    *amd64* )
-              nfssrv=/kernel/misc/amd64/nfssrv
-              afs=/kernel/$DRVFS/amd64/afs ;;
-    *sparcv9* )
-              nfssrv=/kernel/misc/sparcv9/nfssrv
-              afs=/kernel/$DRVFS/sparcv9/afs ;;
-          * )
-              nfssrv=/kernel/misc/nfssrv
-              afs=/kernel/$DRVFS/afs ;;
-esac
-
-
-#
-# Load kernel extensions
-#
-# nfssrv has to be loaded first
-
-
-if [ -f $nfssrv ]; then
+    fi
+    
+    ## Determine if we are running the 64 bit OS
+    ## If sparcv9 then the location of the afs and nfs extensions differ
+    
+    case `isalist` in
+      *amd64* )
+        nfssrv=/kernel/misc/amd64/nfssrv
+        afs=/kernel/$DRVFS/amd64/afs ;;
+      *sparcv9* )
+        nfssrv=/kernel/misc/sparcv9/nfssrv
+        afs=/kernel/$DRVFS/sparcv9/afs ;;
+      * )
+        nfssrv=/kernel/misc/nfssrv
+        afs=/kernel/$DRVFS/afs ;;
+    esac
+    
+    
+    #
+    # Load kernel extensions
+    #
+    # nfssrv has to be loaded first
+    
+    
+    if [ -f $nfssrv ]; then
       echo "Loading NFS server kernel extensions"
       modload $nfssrv
-else
+    else
       echo "$nfssrv does not exist. Skipping AFS startup."
       exit 1
-fi
-
-## Load AFS kernel extensions
-
-if [ -f $afs ]; then
+    fi
+    
+    ## Load AFS kernel extensions
+    
+    if [ -f $afs ]; then
       echo "Loading AFS kernel extensions"
       if issol11; then
         if [ -f /kernel/drv/afs.conf ] ; then
@@ -183,104 +180,108 @@ if [ -f $afs ]; then
       else
         modload $afs
       fi
-else
+    else
       echo "$afs does not exist. Skipping AFS startup."
       exit 1
-fi
-
-#
-# Check that all of the client configuration files exist
-#
-
-for file in /usr/vice/etc/afsd /usr/vice/etc/cacheinfo \
-          /usr/vice/etc/ThisCell /usr/vice/etc/CellServDB
-do
+    fi
+    
+    #
+    # Check that all of the client configuration files exist
+    #
+    
+    for file in /usr/vice/etc/afsd /usr/vice/etc/cacheinfo \
+      /usr/vice/etc/ThisCell /usr/vice/etc/CellServDB
+    do
       if [ ! -f ${file} ]; then
-              echo "${file} does not exist. Not starting AFS client."
-              exit 1
+        echo "${file} does not exist. Not starting AFS client."
+        exit 1
       fi
-done
-
-#
-# Check that the root directory for AFS (/afs) 
-# and the cache directory (/usr/vice/cache) both exist
-#
-
-for dir in `awk -F: '{print $1, $2}' /usr/vice/etc/cacheinfo`
-do
+    done
+    
+    #
+    # Check that the root directory for AFS (/afs) 
+    # and the cache directory (/usr/vice/cache) both exist
+    #
+    
+    for dir in `awk -F: '{print $1, $2}' /usr/vice/etc/cacheinfo`
+    do
       if [ ! -d ${dir} ]; then
-              echo "${dir} does not exist. Not starting AFS client."
-              exit 2
+        echo "${dir} does not exist. Not starting AFS client."
+        exit 2
       fi
-done
-
-echo "Starting $DAEMON "
-if chkafsd; then
-  echo " -> already running"
-else
-  $DAEMON_BIN $AFSD_ARGS
-  RETVAL=$?
-  if [ $RETVAL -eq 0 ]; then
-    setsuid
-    if issol11; then
-      setsysname
-    fi
-    get_cell
-    SETSERVERPREFS=/afs/$CELL/afsadm/sbin/afs_setserverprefs.sh
-    # background job that should run after the AFS initialization...
-    (sleep 60; [ -x $SETSERVERPREFS ] && $SETSERVERPREFS) </dev/null >/dev/null 2>&1 &
-  fi
-fi
-
-  echo ;;
-
-'stop')
-
-#
-# Stop the AFS client
-# Note that the afsd processes cannot be killed
-#
-
-echo "Stopping openafs-client: "
-if chkafsd; then
-  umount $AFS
-  RETVAL=$?
-  echo
-  if [ $RETVAL -eq 0 ] ; then
-    $DAEMON_BIN -shutdown
-    MODID=`modinfo -c | awk '/ afs / {print $1}'`
-    modunload -i $MODID
-    RETVAL=$?
-    if [ $RETVAL -eq 0 ] ; then
-      echo "Kernel module afs unloaded "
+    done
+    
+    echo "Starting $DAEMON "
+    if chkafsd; then
+      echo " -> already running"
     else
-      echo "Problems to unload kernel module "
+      $DAEMON_BIN $AFSD_ARGS
+      RETVAL=$?
+      if [ $RETVAL -eq 0 ]; then
+        setsuid
+        if issol11; then
+          setsysname
+        fi
+        get_cell
+        SETSERVERPREFS=/afs/$CELL/afsadm/sbin/afs_setserverprefs.sh
+        # background job that should run after the AFS initialization...
+        (sleep 60; [ -x $SETSERVERPREFS ] && $SETSERVERPREFS) </dev/null >/dev/null 2>&1 &
+      fi
     fi
-  fi
-else
-  echo " -> $DAEMON not running"
-fi
-echo ;;
 
-'check')
-#
-# Check the running AFS client
-#
+    echo ;;
 
-  echo "Checking openafs-client: "
-  if chkafsd; then
-    get_cell
-    HEALTHCHECK=/afs/$CELL/afsadm/bin/afs_site_health_check.sh
-    if [ -f $HEALTHCHECK ]; then
-      $HEALTHCHECK
+  'stop')
+
+    #
+    # Stop the AFS client
+    # Note that the afsd processes cannot be killed
+    #
+		if noroot_check; then
+		  echo "Script has to be run as root"
+		  exit 1
+		fi
+    echo "Stopping openafs-client: "
+    if chkafsd; then
+      umount $AFS
+      RETVAL=$?
+      echo
+      if [ $RETVAL -eq 0 ] ; then
+        $DAEMON_BIN -shutdown
+        MODID=`modinfo -c | awk '/ afs / {print $1}'`
+        modunload -i $MODID
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ] ; then
+          echo "Kernel module afs unloaded "
+        else
+          echo "Problems to unload kernel module "
+        fi
+      fi
     else
-      echo "Check-script not available: $HEALTHCHECK"
+      echo " -> $DAEMON not running"
     fi
-  else
-    echo "Cannot check openafs-client: not running"
-  fi
-  echo ;;
+    echo ;;
 
-*)    echo "Usage: $0 {start|stop|check}"
-      exit 1;;
+  'check')
+    #
+    # Check the running AFS client
+    #
+    
+    echo "Checking openafs-client: "
+    if chkafsd; then
+      get_cell
+      HEALTHCHECK=/afs/$CELL/afsadm/bin/afs_site_health_check.sh
+      if [ -f $HEALTHCHECK ]; then
+        $HEALTHCHECK
+      else
+        echo "Check-script not available: $HEALTHCHECK"
+      fi
+    else
+      echo "Cannot check openafs-client: not running"
+    fi
+    echo ;;
+    
+  *)
+	  echo "Usage: $0 {start|stop|check}"
+    exit 1;;
 esac
