Fix logic in check_kernelpackages to support kernel-debug, also replacing ps-grep with pgrep, fix routine for getting OS

diff --git a/files/openafs-client-RedHat-init b/files/openafs-client-RedHat-init
--- a/files/openafs-client-RedHat-init
+++ b/files/openafs-client-RedHat-init
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Copyright (c) 2020 AFS-Core Ericsson
-# Version v1.24, 2020-06-17
+# Version v1.25, 2020-07-15
 #
 # openafs-client	Start/Stop the OpenAFS Client
 #
@@ -67,10 +67,10 @@ lock_routine() {
 
 setsuid() {
   if [ -f $SUIDCELLS ]; then
-    for CELLS in $(grep '^[^#]' $SUIDCELLS); do
+    while read -r CELLS; do
       echo "Setting $CELLS suid"
       fs setcell -cell $CELLS -suid
-    done
+    done <<<"$(grep '^[^#]' $SUIDCELLS)"
   fi
 }
 
@@ -99,7 +99,7 @@ get_dist_release() {
           OS="openSuse"
           _DIST="osuse"
         else
-          OS=$(echo "$LsbDescription" -sd | cut -f1-4 -d" " | tr -cs '[:alpha:]' '[\n*]' | grep -v '^$' | cut -c1 | tr -d '[\n]')
+          OS=$(echo "$LsbDescription" | cut -f1-4 -d" " | sed -e 's/\([a-zA-Z]\)[^ ]* */\1/g' -e 's/"//')
           _DIST="sle"
           if [[ $LsbRelease != *.* ]]; then
             patchlevel=$(awk '/^PATCHLEVEL/ {print $3}' /etc/SuSE-release 2>/dev/null)
@@ -173,7 +173,7 @@ setsysname() {
 killafs() {
   SIGNAL=$1
   PIDS=$(lsof -Fp $AFS | sed -e 's/p//')
-  if [ "x" != "x$PIDS" ]; then
+  if [ -n "$PIDS" ]; then
     kill -$SIGNAL $PIDS >/dev/null 2>&1
     sleep 3
   fi
@@ -197,11 +197,18 @@ dkms_check() {
 
 check_kernelpackages() {
   KERNEL_VERSION="$1"
-  if [ -n "$KERNEL_VERSION" ]; then
-    if ! { rpm -q kernel-headers-$KERNEL_VERSION kernel-devel-$KERNEL_VERSION; } >/dev/null 2>&1; then
-      echo "Needed packages for running kernel $KERNEL_VERSION missing: kernel-headers-$KERNEL_VERSION kernel-devel-$KERNEL_VERSION"
+  if [[ "$KERNEL_VERSION" =~ \.debug$ ]]; then
+    KERNEL_CHECK=$(sed -e 's/\.debug$//' <<<$KERNEL_VERSION)
+    KERNEL_DEVEL="debug-devel-$KERNEL_CHECK"
+  else
+    KERNEL_CHECK=$KERNEL_VERSION
+    KERNEL_DEVEL="devel-$KERNEL_VERSION"
+  fi
+  if [ -n "$KERNEL_CHECK" ]; then
+    if ! { rpm -q kernel-headers-$KERNEL_CHECK kernel-$KERNEL_DEVEL; } >/dev/null 2>&1; then
+      echo "Needed packages for running kernel $KERNEL_VERSION missing: kernel-headers-$KERNEL_CHECK kernel-$KERNEL_DEVEL"
       echo "Try to install..."
-      yum --nogpgcheck -q -y install kernel-headers-$KERNEL_VERSION kernel-devel-$KERNEL_VERSION
+      yum --nogpgcheck -q -y install kernel-headers-$KERNEL_CHECK kernel-$KERNEL_DEVEL
       CHKKERNELPACK="false"
     fi
   fi
@@ -320,9 +327,8 @@ check_kernelmodule() {
     fi
     [ $RETVAL -eq 0 ] && rm -f $KMOD_BUILDLOG && echo -n "Build succeded!" && success "Build succeded!" && echo && return 0
 
-    echo "Failed to build kernel module."
-    failure "Failed to build kernel module."
-    echo "See $KMOD_BUILDLOG for more details."
+    echo "Failed to build kernel module, see $KMOD_BUILDLOG for more details. "
+    failure "Failed to build kernel module, see $KMOD_BUILDLOG for more details."
     echo
     return 1
   else
@@ -502,7 +508,7 @@ stop-force() {
     echo
     return 1
   fi
-  if ps ax | grep -q '\[afsd\]'; then
+  if pgrep -xf 'afsd' &>/dev/null; then
     echo
     echo "Sending all processes using $AFS the TERM signal ..."
     killafs TERM
